services:
  - type: web
    name: matrimonial-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    disk:
      name: app-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
